export let DOMAIN_BACKEND: string;
DOMAIN_BACKEND = 'http://localhost:8000/';
DOMAIN_BACKEND = 'http://192.168.0.107:8000/';
export const DOMAIN_API = `${DOMAIN_BACKEND}api/`;
export const DOMAIN_IMG = `${DOMAIN_BACKEND}images/`;
export const IMG_NULL = `${DOMAIN_BACKEND}images/avatar.jpg`;
export const DOMAIN_STATIC = `${DOMAIN_BACKEND}static/`;
export const AUDIO_BELL = `${DOMAIN_STATIC}audio_call_file.mp3`;
export const ACTIVE = 'ACTIVE';
export const INACTIVE = 'INACTIVE';
export const TOKEN_KEY = 'accessToken';
export const TIMES_FOR_WAITING_CALL = 6;